### ISSUE TITLE
How To Access Aisound core voices?

### ISSUE THREAD

**Issue by Elshara** [tsengwoody/WorldVoice#14]
Hello,
the documentation seems pretty straight forward, if a little vague on how to install VECore voices. Assuming this means vocalizer expressive.
But how do you get AI Sound Core voices to install, and what engine does it use? Is it like the Neural Piper voices? Access to install or index the required .zip files would be extremely helpful.
Thanks!

**Comment by lbk2907** [comment]
I got those voices but I forgot where I got those. If you want, I can send
it to you.

**Comment by lbk2907** [comment]
@Elshara
Here's the AISound that you requested. I found it somewhere. Since it's located in another repository, I'll drop the link here:
https://github.com/nvdacn/AiSound5

1. Manually add AISound to WorldVoice:
   - Create a folder named "WorldVoice-workspace". Inside that folder, create another folder called "aisound".
   - The location of the folder will be:
     `%appdata%\nvda\WorldVoice-workspace\aisound`
   - Place the "aisound.dll" inside the "aisound" folder.

2. Package AISound with WorldVoice:
   - Zip the "aisound.dll" and rename the zipped file to "aisound.zip".
   - If you haven't done so before, unpack the WorldVoice add-on package. Simply change the extension from ".nvda-addon" to ".zip" and extract the contents.
   - Inside the extracted folder, create a folder called "Core".
   - Place the "aisound.zip" inside the "Core" folder.
   - Navigate out from the "Core" folder, select all the contents, and zip them.
   - Rename the extension of the zip file from ".zip" to ".nvda-addon".
   - Install the newly packed add-on as you usually would.

**Comment by Elshara** [comment]
Wow! Thank you so much! This is great work!
